// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3sJYb9TgAZ4RF2w6J9hM38GsH6zRGmA',
    appId: '1:1090864952884:web:9f294bb2d7108b03defc61',
    messagingSenderId: '1090864952884',
    projectId: 'character-recognizer-6b402',
    authDomain: 'character-recognizer-6b402.firebaseapp.com',
    storageBucket: 'character-recognizer-6b402.appspot.com',
    measurementId: 'G-8KZ8QLYFVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfirJCxS7BppZPenDoKuWfcAPzDiu1Xg',
    appId: '1:1090864952884:android:fa35da23ccbff163defc61',
    messagingSenderId: '1090864952884',
    projectId: 'character-recognizer-6b402',
    storageBucket: 'character-recognizer-6b402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrFUBI6dJo3Pb6cF5EfVOdPEVLwbvNPOU',
    appId: '1:1090864952884:ios:59d50035b593c3f2defc61',
    messagingSenderId: '1090864952884',
    projectId: 'character-recognizer-6b402',
    storageBucket: 'character-recognizer-6b402.appspot.com',
    iosClientId: '1090864952884-upjgp7snc3e54b8puenmm6p6af1d5jik.apps.googleusercontent.com',
    iosBundleId: 'com.example.opticalCharacterRecognizer',
  );
}
